name: runescape-rujak
base: core18
version: '0.7'
summary: Unoficial RuneScape Game Client 
  RuneScape is a massively multiplayer online role-playing game created by Jagex Ltd..  This
  client allows you to play the game as never before!  By installing this software you are
  agreeing to the End User Licence Agreement (see /usr/share/doc/runescape-launcher
  copyright).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  desktop-gtk2:
    source: .
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - build-essential
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - locales-all
      - libappindicator1
      - xdg-user-dirs
      - ibus-gtk
      - libibus-1.0-5

  glew:
    plugin: dump
    source: http://launchpadlibrarian.net/161405671/libglew1.10_1.10.0-3_amd64.deb
    source-type: deb

  runescape-launcher:
    plugin: dump
    source: https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.6_amd64.deb
    source-type: deb
    override-build: |
      sudo apt update
      sudo apt install libcurl3 -y
      sed -i 's|Icon=runescape|Icon=/usr/share/icons/hicolor/256x256/apps/runescape.png|g' usr/share/applications/runescape-launcher.desktop
      snapcraftctl build
    after:
      - desktop-gtk2
    stage-packages:
      - libsdl2-2.0-0
      - libcurl3-gnutls
      - libstdc++6
      - libgcc1
      - libvorbisenc2
      - libwebkitgtk-1.0-0
      - libcanberra-gtk-module
      - libatk-adaptor
      - libgail-common
      - overlay-scrollbar-gtk2
      - gtk2.0-examples
      - libgtk2.0-0
      - zlib1g
      - libcurl3
      - multiarch-support
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libgl1
      - libterm-readline-perl-perl

apps:
  runescape-launcher:
    command: bin/desktop-launch $SNAP/usr/share/games/runescape-launcher/runescape
    environment:
      PULSE_LATENCY_MSEC: 140
      MESA_GL_VERSION_OVERRIDE: 4.5
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - network
      - pulseaudio
      - opengl
      - gsettings
